package com.tzy.exception;

public class TestException {
	public static void main(String[] args) {
		int[] a = {1,3,4};
		try{
			
		}finally{
			
		}
	}
}
